const DEFAULT_VIEW_PANE_WIDTH = '50%';
const DEFAULT_META_SECTION_HEADING_LEVEL = 3;

const MAX_CHAR_SHORT = 36;
const MAX_CHAR_LONG = 255;

export {
  DEFAULT_VIEW_PANE_WIDTH,
  DEFAULT_META_SECTION_HEADING_LEVEL,
  MAX_CHAR_SHORT,
  MAX_CHAR_LONG,
};
